version: "3.8"
services:
  asit:
    build:
      context: .
      dockerfile: Dockerfile
    image: uchina/asit
    container_name: asit
    volumes:
      - type: bind
        source: .
        target: /myasit
    stdin_open: true
    tty: true
    working_dir: /