FROM alpine
RUN apk add --no-cache gcc g++ make libc-dev cmake clang gmp-dev vim git
RUN	git clone https://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:x-oauth-basic@github.com/uchina1/my_mcl.git 

WORKDIR /my_mcl
