FROM alpine
RUN apk add --no-cache gcc g++ make libc-dev cmake clang gmp-dev vim git
RUN	git clone https://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:x-oauth-basic@github.com/uchina1/my_mcl.git 

WORKDIR /my_mcl
