FROM alpine
RUN apk add --no-cache gcc g++ make libc-dev cmake clang gmp-dev vim git
RUN	git clone https://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:x-oauth-basic@github.com/uchina1/my_mcl.git 

WORKDIR /my_mcl
