apiVersion: v1
kind: Pod
metadata:
  name: aug-verifier-aggs
  labels:
    role: woker
    aggs: vir
spec:
  containers:
    - name: verifier
      image: public.ecr.aws/g4u3m4s4/asit:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: aggs
          containerPort: 1235
          protocol: TCP
      tty: true
      command:
        - sh
        - -c
        - "cd /my_mcl && git pull \
           && make ./bin/aug_server2.exe \
           && sleep 9000000"
      #args: ["192.168.35.168","3000"]
  restartPolicy: OnFailure
  nodeSelector:
    role: verifier