apiVersion: v1
kind: Pod
metadata:
  name: signer-aggs
  labels:
    role: woker
    aggs: sir
spec:
  containers:
    - name: signer
      image: uchina/asit
      ports:
        - name: aggs
          containerPort: 1234
          protocol: TCP
      tty: true
      command:
        - sh
        - -c
        - "cd /my_mcl && git pull \
          && make ./bin/client.exe \
          && ./bin/client.exe 10.244.4.15 \
          && sleep 6000"
      #args: ["192.168.35.168","3000"]
  restartPolicy: OnFailure
  nodeSelector:
    aggs: sir1