apiVersion: v1
kind: Pod
metadata:
  name: sw-1-aggregator-aggs
  labels:
    role: woker
    aggs: agg
spec:
  containers:
    - name: aggregator
      image: public.ecr.aws/g4u3m4s4/asit:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: aggs
          containerPort: 1234
          protocol: TCP
      tty: true
      command:
        - sh
        - -c
        - "cd /my_mcl && git pull \
          && make ./bin/sw-1_aggregator2.exe \
          && sleep 9000000"
      #args: ["10.100.94.214","3000","3000"] # 10.100.104.221
  restartPolicy: Never
  nodeSelector:
    role: aggregator