apiVersion: v1
kind: Pod
metadata:
  name: verifier-aggs
  labels:
    role: woker
    aggs: vir
spec:
  containers:
    - name: verifier
      image: asit
      imagePullPolicy: IfNotPresent
      ports:
        - name: aggs
          containerPort: 1235
          protocol: TCP
      tty: true
      command:
        - sh
        - -c
        - "cd /my_mcl && git pull \
           && make ./bin/server2.exe \
           && sleep 6000"
      #args: ["192.168.35.168","3000"]
  restartPolicy: OnFailure
  nodeSelector:
    aggs: vir